/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FreeQuoteRouteImport } from './routes/free-quote'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as InvoiceTokenRouteImport } from './routes/invoice.$token'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminQuotesIdRouteImport } from './routes/_authenticated/admin/quotes/$id'
import { Route as AuthenticatedPortalQuotesIdRouteImport } from './routes/_authenticated/portal/quotes/$id'
import { Route as ApiPublicAuthHooksPasswordCheckRouteImport } from './routes/api/public/auth-hooks/password-check'
import { Route as ApiPublicCronEngagementRouteImport } from './routes/api/public/cron/engagement'
import { Route as ApiPublicHyperswitchWebhookRouteImport } from './routes/api/public/hyperswitch/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeQuoteRoute = FreeQuoteRouteImport.update({
  id: '/free-quote',
  path: '/free-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuotesIdRoute =
  AuthenticatedAdminQuotesIdRouteImport.update({
    id: '/admin/quotes/$id',
    path: '/admin/quotes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalQuotesIdRoute =
  AuthenticatedPortalQuotesIdRouteImport.update({
    id: '/portal/quotes/$id',
    path: '/portal/quotes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthHooksPasswordCheckRoute =
  ApiPublicAuthHooksPasswordCheckRouteImport.update({
    id: '/api/public/auth-hooks/password-check',
    path: '/api/public/auth-hooks/password-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEngagementRoute = ApiPublicCronEngagementRouteImport.update({
  id: '/api/public/cron/engagement',
  path: '/api/public/cron/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHyperswitchWebhookRoute =
  ApiPublicHyperswitchWebhookRouteImport.update({
    id: '/api/public/hyperswitch/webhook',
    path: '/api/public/hyperswitch/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/portal/quotes/$id': typeof AuthenticatedPortalQuotesIdRoute
  '/api/public/auth-hooks/password-check': typeof ApiPublicAuthHooksPasswordCheckRoute
  '/api/public/cron/engagement': typeof ApiPublicCronEngagementRoute
  '/api/public/hyperswitch/webhook': typeof ApiPublicHyperswitchWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/portal/quotes/$id': typeof AuthenticatedPortalQuotesIdRoute
  '/api/public/auth-hooks/password-check': typeof ApiPublicAuthHooksPasswordCheckRoute
  '/api/public/cron/engagement': typeof ApiPublicCronEngagementRoute
  '/api/public/hyperswitch/webhook': typeof ApiPublicHyperswitchWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/_authenticated/portal/quotes/$id': typeof AuthenticatedPortalQuotesIdRoute
  '/api/public/auth-hooks/password-check': typeof ApiPublicAuthHooksPasswordCheckRoute
  '/api/public/cron/engagement': typeof ApiPublicCronEngagementRoute
  '/api/public/hyperswitch/webhook': typeof ApiPublicHyperswitchWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/free-quote'
    | '/industries'
    | '/privacy'
    | '/security'
    | '/services'
    | '/terms'
    | '/auth/callback'
    | '/invoice/$token'
    | '/portfolio/$slug'
    | '/proposal/$token'
    | '/resources/$slug'
    | '/portfolio/'
    | '/resources/'
    | '/admin/import'
    | '/admin/'
    | '/portal/'
    | '/admin/quotes/$id'
    | '/portal/quotes/$id'
    | '/api/public/auth-hooks/password-check'
    | '/api/public/cron/engagement'
    | '/api/public/hyperswitch/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/free-quote'
    | '/industries'
    | '/privacy'
    | '/security'
    | '/services'
    | '/terms'
    | '/auth/callback'
    | '/invoice/$token'
    | '/portfolio/$slug'
    | '/proposal/$token'
    | '/resources/$slug'
    | '/portfolio'
    | '/resources'
    | '/admin/import'
    | '/admin'
    | '/portal'
    | '/admin/quotes/$id'
    | '/portal/quotes/$id'
    | '/api/public/auth-hooks/password-check'
    | '/api/public/cron/engagement'
    | '/api/public/hyperswitch/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/free-quote'
    | '/industries'
    | '/privacy'
    | '/security'
    | '/services'
    | '/terms'
    | '/auth_/callback'
    | '/invoice/$token'
    | '/portfolio/$slug'
    | '/proposal/$token'
    | '/resources/$slug'
    | '/portfolio/'
    | '/resources/'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/quotes/$id'
    | '/_authenticated/portal/quotes/$id'
    | '/api/public/auth-hooks/password-check'
    | '/api/public/cron/engagement'
    | '/api/public/hyperswitch/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FreeQuoteRoute: typeof FreeQuoteRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ProposalTokenRoute: typeof ProposalTokenRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiPublicAuthHooksPasswordCheckRoute: typeof ApiPublicAuthHooksPasswordCheckRoute
  ApiPublicCronEngagementRoute: typeof ApiPublicCronEngagementRoute
  ApiPublicHyperswitchWebhookRoute: typeof ApiPublicHyperswitchWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-quote': {
      id: '/free-quote'
      path: '/free-quote'
      fullPath: '/free-quote'
      preLoaderRoute: typeof FreeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quotes/$id': {
      id: '/_authenticated/admin/quotes/$id'
      path: '/admin/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/quotes/$id': {
      id: '/_authenticated/portal/quotes/$id'
      path: '/portal/quotes/$id'
      fullPath: '/portal/quotes/$id'
      preLoaderRoute: typeof AuthenticatedPortalQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth-hooks/password-check': {
      id: '/api/public/auth-hooks/password-check'
      path: '/api/public/auth-hooks/password-check'
      fullPath: '/api/public/auth-hooks/password-check'
      preLoaderRoute: typeof ApiPublicAuthHooksPasswordCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/engagement': {
      id: '/api/public/cron/engagement'
      path: '/api/public/cron/engagement'
      fullPath: '/api/public/cron/engagement'
      preLoaderRoute: typeof ApiPublicCronEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperswitch/webhook': {
      id: '/api/public/hyperswitch/webhook'
      path: '/api/public/hyperswitch/webhook'
      fullPath: '/api/public/hyperswitch/webhook'
      preLoaderRoute: typeof ApiPublicHyperswitchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedAdminQuotesIdRoute: typeof AuthenticatedAdminQuotesIdRoute
  AuthenticatedPortalQuotesIdRoute: typeof AuthenticatedPortalQuotesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedAdminQuotesIdRoute: AuthenticatedAdminQuotesIdRoute,
  AuthenticatedPortalQuotesIdRoute: AuthenticatedPortalQuotesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FreeQuoteRoute: FreeQuoteRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ProposalTokenRoute: ProposalTokenRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiPublicAuthHooksPasswordCheckRoute: ApiPublicAuthHooksPasswordCheckRoute,
  ApiPublicCronEngagementRoute: ApiPublicCronEngagementRoute,
  ApiPublicHyperswitchWebhookRoute: ApiPublicHyperswitchWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
