// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptvwcblnkumrhiohavvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dndjYmxua3Vtcmhpb2hhdnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0NjAzNjIsImV4cCI6MjEwMTAzNjM2Mn0.fMK3O07EJ-XKknnuVH_Guam2EUx23SU_VKuLqcxviNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});